// <auto-generated />
namespace Clinic.BackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedlogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedlogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201509171753426_Added logs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
