//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.BackEnd.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Appointment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Appointment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clinic.BackEnd.Models.Resources.Appointment", typeof(Appointment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anovulant.
        /// </summary>
        public static string Anovulant {
            get {
                return ResourceManager.GetString("Anovulant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        public static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBB 1.
        /// </summary>
        public static string COBB1 {
            get {
                return ResourceManager.GetString("COBB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBB 2.
        /// </summary>
        public static string COBB2 {
            get {
                return ResourceManager.GetString("COBB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBB 3.
        /// </summary>
        public static string COBB3 {
            get {
                return ResourceManager.GetString("COBB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBB 4.
        /// </summary>
        public static string COBB4 {
            get {
                return ResourceManager.GetString("COBB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string CobbCondition {
            get {
                return ResourceManager.GetString("CobbCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corset.
        /// </summary>
        public static string Corset {
            get {
                return ResourceManager.GetString("Corset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CorsetComment {
            get {
                return ResourceManager.GetString("CorsetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End.
        /// </summary>
        public static string CorsetDateEnd {
            get {
                return ResourceManager.GetString("CorsetDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start.
        /// </summary>
        public static string CorsetDateStart {
            get {
                return ResourceManager.GetString("CorsetDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pain.
        /// </summary>
        public static string Pain {
            get {
                return ResourceManager.GetString("Pain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risser.
        /// </summary>
        public static string Risser {
            get {
                return ResourceManager.GetString("Risser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke per day.
        /// </summary>
        public static string SmokePerDay {
            get {
                return ResourceManager.GetString("SmokePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoker.
        /// </summary>
        public static string Smoker {
            get {
                return ResourceManager.GetString("Smoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
