//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.BackEnd.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Participant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Participant() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clinic.BackEnd.Models.Resources.Participant", typeof(Participant).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHS-Patient #.
        /// </summary>
        public static string CHS {
            get {
                return ResourceManager.GetString("CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor_Id {
            get {
                return ResourceManager.GetString("Doctor_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Animals.
        /// </summary>
        public static string DomesticAnimals {
            get {
                return ResourceManager.GetString("DomesticAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic Precision.
        /// </summary>
        public static string EthnicPrecision {
            get {
                return ResourceManager.GetString("EthnicPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family History.
        /// </summary>
        public static string FamilyHistory {
            get {
                return ResourceManager.GetString("FamilyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age start smoking.
        /// </summary>
        public static string FatherSmokingAge {
            get {
                return ResourceManager.GetString("FatherSmokingAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number per day.
        /// </summary>
        public static string FatherSmokingNumber {
            get {
                return ResourceManager.GetString("FatherSmokingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Group.
        /// </summary>
        public static string FunctionalGroup {
            get {
                return ResourceManager.GetString("FunctionalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSJ-Patient #.
        /// </summary>
        public static string HSJ {
            get {
                return ResourceManager.GetString("HSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Sign Off.
        /// </summary>
        public static string IsConsent {
            get {
                return ResourceManager.GetString("IsConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking .
        /// </summary>
        public static string IsFatherSmoking {
            get {
                return ResourceManager.GetString("IsFatherSmoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string IsMale {
            get {
                return ResourceManager.GetString("IsMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking while pregnant.
        /// </summary>
        public static string IsMotherSmoking {
            get {
                return ResourceManager.GetString("IsMotherSmoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        public static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCH-Patient #.
        /// </summary>
        public static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History.
        /// </summary>
        public static string MedicalHistory {
            get {
                return ResourceManager.GetString("MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History Other.
        /// </summary>
        public static string MedicalHistoryOther {
            get {
                return ResourceManager.GetString("MedicalHistoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menarche.
        /// </summary>
        public static string Menarche {
            get {
                return ResourceManager.GetString("Menarche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age start smoking.
        /// </summary>
        public static string MotherSmokingAge {
            get {
                return ResourceManager.GetString("MotherSmokingAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number per day.
        /// </summary>
        public static string MotherSmokingNumber {
            get {
                return ResourceManager.GetString("MotherSmokingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age the patient start smoking.
        /// </summary>
        public static string ParticipantSmokingAge {
            get {
                return ResourceManager.GetString("ParticipantSmokingAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random #.
        /// </summary>
        public static string RandomId {
            get {
                return ResourceManager.GetString("RandomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Year.
        /// </summary>
        public static string SchoolYear {
            get {
                return ResourceManager.GetString("SchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Adress.
        /// </summary>
        public static string StreetAdress {
            get {
                return ResourceManager.GetString("StreetAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery Date.
        /// </summary>
        public static string SurgeryDate {
            get {
                return ResourceManager.GetString("SurgeryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery.
        /// </summary>
        public static string SurgeryType {
            get {
                return ResourceManager.GetString("SurgeryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
    }
}
